---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks.git
      sha: v2.2.1
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-json
          - id: check-yaml
          - id: debug-statements
          - id: check-merge-conflict
    - repo: https://github.com/asottile/seed-isort-config
      rev: v1.8.0
      hooks:
          - id: seed-isort-config
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: 'v4.3.18'
      hooks:
          - id: isort
            files: 'preview_generator/(.*)/*.py'
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: 'v4.3.18'
      hooks:
      - id: isort
        files: 'tests/(.*)/*.py'
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
          - id: black
            language_version: python3.6
            args: [-l 100]
            files: 'preview_generator'
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
          - id: black
            language_version: python3.6
            args: [-l 100]
            files: 'tests'
